### PR TITLE
Rewrite table people problem

### PR DESCRIPTION
**Pull request by liusida**

### CODE REVIEW

**Comment by zimoliu-vt** [comment]
please add testing i do not trust it

**Comment by zimoliu-vt** [comment]
11212312341234512345612345671234567812345678912345678901234567891011121314151617181920

**Review by zimoliu-vt — APPROVED** [review]
good to go

**Review by liusida — COMMENTED** [review]
Rewrite table people problem with unitest

**Review by zimoliu-vt — APPROVED** [review]
ok

**Pull request merged**
